linters-settings:
  depguard:
    rules:
      main:
        list-mode: strict
        files:
          - $all
          - "!**/analysis/*.go"
          - "!**/codeactions/*.go"
          - "!**/diagnostics/*.go"
          - "!**/lsp/*.go"
          - "!**/rpc/*.go"
          - "!**/state/*.go"
        allow:
          - $gostd
          - github.com/chefe/copyrightlsp/analysis
          - github.com/chefe/copyrightlsp/lsp
          - github.com/chefe/copyrightlsp/state
          - github.com/chefe/copyrightlsp/diagnostics
          - github.com/chefe/copyrightlsp/codeactions
          - github.com/chefe/copyrightlsp/rpc

      analysis:
        list-mode: strict
        files:
          - "**/analysis/*.go"
        allow:
          - $gostd

      codeactions:
        list-mode: strict
        files:
          - "**/codeactions/*.go"
        allow:
          - $gostd
          - github.com/chefe/copyrightlsp/analysis
          - github.com/chefe/copyrightlsp/lsp
          - github.com/chefe/copyrightlsp/state

      diagnostics:
        list-mode: strict
        files:
          - "**/diagnostics/*.go"
        allow:
          - $gostd
          - github.com/chefe/copyrightlsp/analysis
          - github.com/chefe/copyrightlsp/lsp
          - github.com/chefe/copyrightlsp/state

      lsp:
        list-mode: strict
        files:
          - "**/lsp/*.go"
        allow:
          - $gostd

      rpc:
        list-mode: strict
        files:
          - "**/rpc/*.go"
        allow:
          - $gostd
          - github.com/chefe/copyrightlsp/rpc

      state:
        list-mode: strict
        files:
          - "**/state/*.go"
        allow:
          - $gostd

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated

  misspell:
    locale: US

  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true

linters:
  enable-all: true
  disable:
    # disable deprecated linters
    - nosnakecase
    - ifshort
    - interfacer
    - golint
    - deadcode
    - exhaustivestruct
    - scopelint
    - structcheck
    - varcheck
    - maligned

    # disable `testpackage` linter because white-box tests are used
    - testpackage

    # temporary disabled until they can be fixed
    - revive
    - wsl
    - stylecheck
    - exhaustruct
    - wrapcheck
    - varnamelen
    - perfsprint
    - paralleltest
    - nonamedreturns
    - nlreturn
    - gocritic
    - gomnd
    - goerr113
    - lll
    - godot
    - unconvert
    - gofumpt
    - gosec

issues:
  exclude-use-default: false

  exclude-rules:
    # disable funlen linter for test funcs
    - source: ^func\ Test.*$
      path: _test\.go
      linters:
        - funlen

    # disable varnamelen linter for tt variable in test funcs
    - source: ^\s*tt := tt$
      path: _test\.go
      linters:
        - varnamelen
